const wordList = {
			Standard: 	[			
    						"mensch", "jahr", "zeit", "tag", "woche",
   						"freund", "arbeit", "nacht", "sache", "hand",
    						"haus", "decke", "kind", "vater", "mutter",
    						"schule", "kindheit", "hilfe", "familie", "gesicht",
    						"auto", "buch", "welt", "problem", "moeglichkeit",
    						"erfolg", "person", "stadt", "arzt", "krankheit",
    						"leben", "stunde", "universitaet", "beruf", "geld",
    						"mittel", "autobahn", "reise", "erfahrung", "politik",
    						"frage", "antwort", "telefon", "adresse", "gebirge",
    						"wohnung", "flughafen", "recht", "gesetz", "freiheit",
    						"freizeit", "quelle", "lektion", "pferd", "getraenk",
    						"bilderrahmen", "baustelle", "technik", "wissenschaft", "tasche",
    						"geschenk", "natur", "licht", "luft", "boden",
    						"wasser", "oberflaeche", "unterstuetzung", "kraft", "staerke",
    						"zukunft", "vergangenheit", "bedeutung", "kultur", "laender",
    						"gesellschaft", "energie", "lust", "gefuehl", "kamera",
    						"sport", "musik", "kunst", "film", "literatur",
    						"idee", "erlebnis", "veraenderung", "fehler", "ereignis",
    						"macht", "bahnhof", "audio", "ziel", "zugang",
    						"sinn", "beziehung", "verhaeltnis", "sprache", "wissen",

    						"laufen", "springen", "fliegen", "sehen", "hoeren",
    						"essen", "trinken", "spielen", "arbeiten", "sitzen",
    						"lesen", "schreiben", "schlafen", "wachen", "denken",
    						"reden", "singen", "malen", "verlassen", "freuen",
    						"tanzen", "kochen", "backen", "reisen", "fahren",
    						"verstehen", "lernen", "fragen", "antworten", "kaufen",
    						"planen", "organisieren", "spazieren", "geniessen", "verlieben",
    						"weinen", "lachen", "klettern", "joggen", "glauben",
    						"umarmen", "unterhalten", "verkaufen", "veraendern", "schminken",
    						"wecken", "aufstehen", "basteln", "zeichnen", "bauen",
    						"raetseln", "ueberlegen", "erklaeren", "anrufen", "entspannen",
    						"vorschlagen", "putzen", "lehren", "forschen", "annehmen",
    						"ablehnen", "machen", "geben", "nehmen", "kommen",
    						"gehen", "bleiben", "bringen", "finden", "suchen",
    						"zeigen", "helfen", "kennen", "lieben", "leben",
    						"warten", "beginnen", "enden", "gewinnen", "verlieren",
    						"oeffnen", "schliessen", "tragen", "halten", "stellen",
    						"legen", "sprechen", "schicken", "rufen", "erzaehlen",
    						"schnell", "langsam", "gross", "klein", "stark",
    						"schwach", "alt", "jung", "neu", "schoen",
					],
				
			Tiere:		[
    						"hund", "katze", "vogel", "loewe", "elefant",
    						"tiger", "baer", "giraffe", "krokodil", "pinguin",
    						"kaenguru", "koala", "pferd", "esel", "zebra",
    						"schaf", "ziege", "rind", "hase", "maus",
    						"ratte", "eichhoernchen", "igel", "schmetterling", "biene",
    						"wolf", "adler", "falke", "amsel", "taube",
    						"schlange", "leguan", "frosch", "kraehe", "marder",
    						"otter", "seehund", "delfin", "robbe", "pfau",
    						"eule", "kauz", "ameise", "spinne", "heuschrecke",
    						"muecke", "kaefer", "schnecke", "lachs", "karpfen",

    						"gorilla", "schimpanse", "orangutan", "gibbon", "pavian",
    						"flusspferd", "nashorn", "antilope", "gazelle", "kamel",
    						"lama", "alpaka", "rentier", "elch", "wildschwein",
    						"hirsch", "fuchs", "dachs", "hamster", "truthahn",
    						"meerschweinchen", "kaninchen", "frettchen", "fledermaus", "maulwurf",
    						"biber", "waschbaer", "panda", "eisbaer", "seeloewe",
    						"walross", "qualle", "krake", "tintenfisch", "seestern",
    						"garnele", "hummer", "schildkroete", "kroete", "salamander",
    						"gecko", "chamaeleon", "python", "kobra", "alligator",
   						"pelikan", "flamingo", "papagei", "kanarienvogel", "specht",
					],
			
			Lebensmittel: 	[			
						"apfel", "banane", "kaese", "brot", "milch",
    						"reis", "kartoffel", "tomate", "salat", "gurke",
    						"zwiebel", "paprika", "karotte", "spinat", "bohnen",
    						"linsen", "erbsen", "joghurt", "butter", "honig",
    						"schokolade", "nudeln", "kaffee", "tee", "olivenoel",
    						"mehl", "eier", "wurst", "schinken", "rindfleisch",
    						"haehnchen", "lachs", "forelle", "tofu", "seitan",
    						"kokosnuss", "mandel", "walnuss", "cashew", "pistazie",
    						"erdnuss", "bananenblatt", "papaya", "ananas", "mango",
    						"kirsche", "erdbeere", "himbeere", "blaubeere", "pfirsich",

   						"birne", "orange", "zitrone", "limette", "kiwi",
    						"melone", "wassermelone", "traube", "pflaume", "aprikose",
    						"nektarine", "granatapfel", "feige", "dattel", "kokosmilch",
    						"avocado", "brokkoli", "blumenkohl", "zucchini", "aubergine",
    						"kuerbis", "mais", "sellerie", "lauch", "knoblauch",
    						"champignon", "spargel", "radieschen", "rotebete", "sauerkraut",
   						"haferflocken", "muesli", "quark", "sahne", "frischkaese",
    						"mozzarella", "parmesan", "camembert", "salami", "speck",
    						"kakao", "marmelade", "senf", "ketchup", "mayonnaise",
    						"essig", "zucker", "salz", "pfeffer", "couscous",
					],
					
		    	Länder: 	[    			
						"deutschland", "frankreich", "italien", "spanien", "portugal",
    						"england", "irland", "norwegen", "schweden", "finnland",
    						"daenemark", "island", "niederlande", "belgien", "schweiz",
    						"oesterreich", "polen", "tschechien", "ungarn", "kroatien",
    						"serbien", "rumaenien", "bulgarien", "griechenland", "albanien",
    						"ukraine", "georgien", "armenien", "kasachstan", "mongolei",
    						"russland", "tuerkei", "israel", "jordanien", "libanon",
    						"aegypten", "marokko", "kenia", "nigeria", "aethiopien",
    						"indien", "china", "japan", "suedkorea", "thailand",
    						"vietnam", "indonesien", "australien", "kanada", "brasilien",
					],

			Städte: 	[      
 						"berlin", "hamburg", "muenchen", "koeln", "frankfurt",
    						"duesseldorf", "stuttgart", "dortmund", "essen", "leipzig",
    						"bremen", "dresden", "hannover", "nuernberg", "duisburg",
    						"bochum", "wuppertal", "bonn", "muenster", "karlsruhe",
    						"augsburg", "wiesbaden", "aachen", "potsdam", "rostock",

    						"paris", "london", "madrid", "rom", "barcelona",
    						"amsterdam", "wien", "zuerich", "prag", "budapest",
    						"moskau", "tokio", "peking", "shanghai", "seoul",
    						"bangkok", "singapur", "dubai", "sydney", "toronto",
    						"chicago", "miami", "newyork", "losangeles", "kairo",
					],

	    		Berufe: 	[       
						"arzt", "lehrer", "polizist", "feuerwehrmann", "pilot",
    						"koch", "baecker", "metzger", "friseur", "verkaeufer",
    						"kellner", "mechaniker", "elektriker", "installateur", "tischler",
    						"maurer", "bauarbeiter", "architekt", "ingenieur", "programmierer",
    						"designer", "fotograf", "journalist", "schriftsteller", "musiker",
    						"saenger", "schauspieler", "taenzer", "kuenstler", "wissenschaftler",
    						"anwalt", "richter", "steuerberater", "buchhalter", "bankkaufmann",
    						"unternehmer", "manager", "sekretaer", "rezeptionist", "taxifahrer",
    						"apotheker", "zahnarzt", "tierarzt", "krankenpfleger", "chirurg",
    						"psychologe", "sportler", "trainer", "gaertner", "landwirt",
					],

			Farben: 	[		
						"rot", "blau", "gruen", "gelb", "orange",
    						"lila", "violett", "pink", "rosa", "braun",
    						"schwarz", "weiss", "grau", "beige", "tuerkis",
    						"gold", "silber", "bronze", "mintgruen", "olivgruen",
    						"dunkelgruen", "hellgruen", "dunkelblau", "hellblau", "dunkelrot",
    						"hellrot", "dunkelgelb", "hellgelb", "dunkelbraun", "hellbraun",
    						"dunkelgrau", "hellgrau", "dunkellila", "helllila", "magenta",
    						"fuchsia", "korallenrot", "bordeaux", "lavendel", "tuerkisblau",
    						"himmelblau", "marineblau", "meerblau", "creme", "khaki",
    						"oliv", "apricot", "pfirsich", "sandfarben", "weinrot",
					],

		    	Eishockey: 	[    
						"puck", "schlaeger", "eis", "tor", "torwart",
    						"stuermer", "verteidiger", "spieler", "kapitaen", "trainer",
    						"schiedsrichter", "bande", "eisflaeche", "schlittschuhe", "helm",
    						"handschuhe", "trikot", "spielerbank", "strafbank", "arena",
    						"tribuene", "liga", "verein", "mannschaft", "nationalmannschaft",
    						"meisterschaft", "weltmeisterschaft", "drittel", "pause", "verlaengerung",
    						"schlagschuss", "distanzschuss", "bodycheck", "zweikampf", "powerplay",
    						"unterzahl", "bully", "abseits", "icing", "assist",
    						"hattrick", "penalty", "penaltyschiessen", "videobeweis", "sirene",
    						"puckkontrolle", "fangquote", "schussgenauigkeit", "fanclub", "zamboni",
					],
	
			Volleyball: 	[   
						"volleyball", "netz", "ball", "aufschlag", "annahme",
    						"pritschen", "baggern", "angriff", "abwehr", "block",
    						"zuspiel", "zuspieler", "spieler", "libero", "trainer",
    						"schiedsrichter", "linienrichter", "punkte", "satz", "satzball",
    						"matchball", "sieg", "niederlage", "auszeit", "rotation",
    						"wechsel", "position", "angriffszone", "dreimeterlinie", "grundlinie",
    						"seitenlinie", "antenne", "netzberuehrung", "uebertritt", "fehler",
    						"ass", "schmetterball", "blocken", "springen", "einspielen",
    						"einschlagen", "mannschaft", "team", "kapitaen", "anfeuern",
    						"kommunikation", "absprache", "pancake", "mittelblocker", "aussenangreifer",
					],
	
			Pflanzen: 	[     
						"eiche", "buche", "birke", "ahorn", "kastanie",
    						"linde", "fichte", "tanne", "kiefer", "weide",
   						"pappel", "esche", "zeder", "eibe", "magnolie",
    						"rose", "tulpe", "lilie", "veilchen", "sonnenblume",
    						"narzisse", "lavendel", "geranie", "pfingstrose", "anemone",
    						"gaensebluemchen", "schneegloeckchen", "krokus", "nelke", "jasmin",
					],

	    		Elemente: 	[     
						"wasserstoff", "helium", "sauerstoff", "kohlenstoff", "stickstoff",
    						"eisen", "gold", "silber", "kupfer", "zink",
    						"aluminium", "magnesium", "natrium", "kalium", "calcium",
    						"chlor", "schwefel", "phosphor", "fluor", "brom",
    						"jod", "quecksilber", "blei", "zinn", "platin",
    						"uran", "radium", "kobalt", "nickel", "titan",
					]	    
        	};
