const wordList = {
		Standard: [		// Nomen (Substantive)
						"mensch", "jahr", "zeit", "tag", "woche", "freund", "arbeit", "nacht", "sache", "hand",
						"haus", "decke", "kind", "vater", "mutter", "schule", "kindheit", "hilfe", "familie", "gesicht",
						"auto", "buch", "welt", "problem", "moeglichkeit", "erfolg", "person", "stadt", "arzt", "krankheit",
						"leben", "stunde", "universitaet", "beruf", "geld", "mittel", "autobahn", "reise", "erfahrung", "politik",
						"frage", "antwort", "telefon", "adresse", "gebirge", "wohnung", "flughafen", "recht", "gesetz", "freiheit",
						"freizeit", "quelle", "lektion", "pferd", "essen", "getraenk", "bilderrahmen", "baustelle", "technik", "wissenschaft",
						"geschenk", "natur", "licht", "luft", "boden", "wasser", "oberflaeche", "unterstuetzung", "kraft", "staerke",
						"zukunft", "vergangenheit", "bedeutung", "kultur", "laender", "gesellschaft", "energie", "lust", "gefuehl",
						"sport", "musik", "kunst", "film", "literatur", "idee", "erlebnis", "veraenderung", "fehler", "ereignis",
						"macht", "bahnhof", "audio", "ziel", "zugang", "sinn", "beziehung", "verhaeltnis", "sprache", "wissen",
						"wahrheit", "baby", "monat", "jahrhundert", "sekunde", "minute", "handy", "computer", "kamera", "tasche",

						// Verben
						"laufen", "springen", "fliegen", "sehen", "hoeren", "essen", "trinken", "spielen", "arbeiten",
						"lesen", "schreiben", "laufen", "schlafen", "wachen", "denken", "reden", "singen", "malen",
						"tanzen", "kochen", "backen", "reisen", "fahren", "verstehen", "lernen", "fragen", "antworten",
						"arbeiten", "planen", "organisieren", "spazieren", "geniessen", "verlieben", "verlassen", "freuen",
						"weinen", "lachen", "klettern", "fahren", "joggen", "schnell", "glauben", "umarmen", "unterhalten",
						"schminken", "wecken", "aufstehen", "basteln", "malen", "zeichnen", "sitzen", "kaufen", "verkaufen",
						"bauen", "arbeiten", "raetseln", "ueberlegen", "erklaeren", "anrufen", "annehmen", "ablehnen",
						"planen", "entspannen", "vorschlagen", "kochen", "putzen", "lehren", "forschen", "veraendern"
	],				
		Tiere: [		"hund", "katze", "vogel", "loewe", "elefant", 
						"tiger", "baer", "giraffe", "krokodil", "pinguin", 
						"kaenguru", "koala", "pferd", "esel", "zebra", 
						"schaf", "ziege", "rind", "hase", "maus", 
						"ratte", "eichhoernchen", "igel", "schmetterling", "biene", 
						"wolf", "adler", "falke", "amsel", "taube", 
						"schlange", "leguan", "frosch", "kraehe", "marder", 
						"otter", "seehund", "wal", "delfin", "robbe", 
						"eule", "kauz", "ameise", "spinne", "heuschrecke", 
						"muecke", "kaefer", "schnecke", "lachs", "karpfen"
	],					
		Lebensmittel: [	"apfel", "banane", "kaese", "brot", "milch", 
						"reis", "kartoffel", "tomate", "salat", "gurke", 
						"zwiebel", "paprika", "karotte", "spinat", "bohnen", 
						"linsen", "erbsen", "joghurt", "butter", "honig", 
						"schokolade", "nudeln", "kaffee", "tee", "olivenoel", 
						"mehl", "eier", "wurst", "schinken", "rindfleisch", 
						"haehnchen", "lachs", "forelle", "tofu", "seitan", 
						"kokosnuss", "mandel", "walnuss", "cashew", "pistazie", 
						"erdnuss", "bananenblatt", "papaya", "ananas", "mango", 
						"kirsche", "erdbeere", "himbeere", "blaubeere", "pfirsich"
	],					
	    Länder: [    	"deutschland", "frankreich", "italien", "spanien", "england", 
						"kanada", "brasilien", "mexiko", "argentinien", "australien", 
						"japan", "china", "indien", "russland", "suedafrika", 
						"aegypten", "marokko", "griechenland", "schweden", "norwegen", 
						"finnland", "daenemark", "niederlande", "belgien", "schweiz", 
						"oesterreich", "polen", "tschechien", "ungarn", "tuerkei", 
						"israel", "kenia", "nigeria", "indonesien", "malaysia", 
						"singapur", "thailand", "vietnam", "philippinen", "suedkorea", 
						"neuseeland", "peru", "chile", "kolumbien", "venezuela", 
						"kuba", "aethiopien", "pakistan", "bangladesch", "ukraine"
	],
		Städte: [       "berlin", "paris", "london", "tokio", "sydney", 
						"moskau", "rio", "shanghai", "dubai", "mumbai", 
						"peking", "kairo", "rom", "istanbul", "seoul", 
						"bangkok", "jakarta", "salzburg", "toronto", "lima", 
						"barcelona", "madrid", "mailand", "hongkong", "singapur", 
						"athen", "wien", "kopenhagen", "koeln", "chicago", 
						"amsterdam", "frankfurt", "zuerich", "dallas", "vancouver", 
						"melbourne", "budapest", "oslo", "stockholm", "muenchen", 
						"kairo", "dallas", "dubai", "montreal", "calgary", 
						"helsinki", "lyon", "hamburg", "reykjavik", "warschau"
	],
	    Berufe: [       "arzt", "lehrer", "ingenieur", "koch", "friseur", 
						"bauarbeiter", "architekt", "elektriker", "kaufmann", "mechaniker", 
						"tierarzt", "journalist", "pilot", "verkaeufer", "designer", 
						"programmierer", "rechtsanwalt", "psychologe", "zahnarzt", "saenger", 
						"taenzer", "kuenstler", "fotograf", "musiker", "wissenschaftler", 
						"polizist", "feuerwehrmann", "soldat", "schneider", "buchhalter", 
						"sekretaer", "rezeptionist", "bibliothekar", "gaertner", "fruehstueckskoch", 
						"zimmermann", "verlagskaufmann", "barkeeper", "kellner", "maler", 
						"landwirt", "taxifahrer", "lkwfahrer", "reiseleiter", "bauleiter", 
						"pharmazeut", "apotheker", "buchhaendler", "dachdecker", "sicherheitsbeauftragter"
	],
		Farben: [		"rot", "blau", "gruen", "gelb", "schwarz", 
						"weiss", "orange", "braun", "violett", "pink", 
						"beige", "tuerkis", "lila", "graublau", "hellblau", 
						"dunkelblau", "hellgruen", "dunkelgruen", "olivgruen", "mintgruen", 
						"lindgruen", "magenta", "zyan", "azurblau", "senfgelb", 
						"bordeaux", "lavendel", "pastellrosa", "pfirsich", "ziegelrot", 
						"graphitgrau", "schiefergrau", "karmesinrot", "champagner", "platin", 
						"kobaltblau", "smaragdgruen", "blassgelb", "creme", "gold", 
						"silber", "bronze", "tuerkisblau", "fuchsia", "mandelbraun", 
						"waldgruen", "eisblau", "schokoladenbraun", "kupfer", "apricot"
	],
	    Eishockey: [    "puck", "schlaeger", "torwart", "stuermer", "verteidiger", 
						"bande", "powerplay", "penalty", "zweikampf", "hattrick", 
						"bully", "abseits", "icing", "assist", "zambioni", 
						"schlagschuss", "meisterschaft", "bodycheck", "drittel", "pause",
						"schlittschuhe", "verlaengerung", "penaltyschiessen", "handschuhe", "trikot", 
						"spielerbank", "eisflaeche", "helm", "puckkontrolle", "strafbank", 
						"schiedsrichter", "einlaufshow", "arena", "nationalmannschaft", "weltmeisterschaft", 
						"wuerfel", "plexiglas", "kampf", "liga", "tribuene", 
						"verein", "tor", "kapitaen", "videobeweis", "sirene", 
						"schussgenauigkeit", "fangquote", "coach", "regelbuch", "fanclub"
	],
	
		Volleyball: [   "pritschen", "baggern", "angriff", "abwehr", "block",
						"springen", "rolle", "diving", "pancake", "zuspiel",
						"dreimeterlinie", "uebertritt", "gehoben", "zuschauer", "annahme",
						"schiedsrichter", "linienrichter", "punkte", "saetze", "satzball",
						"matchball", "sieg", "niederlage", "libero", "libera",
						"mittelblocker", "aussenannahme", "diagonal", "zuspieler", "trikots",
						"trainer", "auszeit", "pfeife", "baelle", "einspielen",
						"einschlagen", "mannschaftskapitaen", "abklatschen", "team", "ass",
						"anfeuern", "aufschlag", "float", "marktplatz", "netzberuehrung",
						"antennen", "aus", "kommunikation", "absprache", "tve"
	],
	
	    Pflanzen: [     "eiche", "birke", "fichte", "kiefer", "ahorn", 
						"linde", "buche", "esche", "tanne", "weide",
						"kastanie", "eibe", "pappel", "zeder", "magnolie", 
						"rose", "tulpe", "lilie", "veilchen", "stiefmuetterchen", 
						"sonnenblume", "narzisse", "hyanzinthe", "schneegloeckchen", "gaensebluemchen",
						"vergissmeinnicht", "lavendel", "pfingstrose", "anemone", "geranie"
	],
	    Elemente: [     "wasserstoff", "helium", "lithium", "zinn", "blei", 
						"kohlenstoff", "stickstoff", "sauerstoff", "fluor", "gold", 
						"natrium", "magnesium", "aluminium", "silicium", "phosphor", 
						"schwefel", "chlor", "argon", "kalium", "calcium", 
						"rhodium", "titan", "silber", "chrom", "palladium", 
						"eisen", "kobalt", "nickel", "kupfer", "zink"
	]	    
        };
